### ISSUE TITLE
Improve facebook module...

### ISSUE THREAD

**Issue by Virgula0** [Ethical-H4CK3R/Pulse#15]
Hi, first of all great work... I tried the facebook module on my own account and I see that after 28 attempts my account locks and the program stopped work... So , for example, if i have to do an attack and testing more than 1000 words as passwords, could be possible add a "waiting" function that for every 20 attempts the program  wait a minute? (it's an indicative time it depend by facebook you can misure it) To avoid the facebook locking system...
Thank you!

I don't have tried instagram and twitter but as I have understand there isn't this locker for these...

**Comment by Ethical-H4CK3R** [comment]
I tried that before, and it didn't work.

**Comment by Virgula0** [comment]
Uhm... ok but I also tried the instagram module on a real account and it doesn't work...

**Comment by Ethical-H4CK3R** [comment]
Does Instagram lock as well?

**Comment by Ethical-H4CK3R** [comment]
You know what, you can have the script, I don’t want it anymore, maintaining is too much, and I need to stay focused on school. So keep it, you can find ways to improve. BTW brute force success rate 2/100 or 2%.

**Comment by firebreed** [comment]
So far it has been working fine for me, no lock what so ever with IG.

**Comment by Virgula0** [comment]
> You know what, you can have the script, I don’t want it anymore, maintaining is too much, and I need to stay focused on school. So keep it, you can find ways to improve. BTW brute force success rate 2/100 or 2%.

Man your work is good don't worry... Update it only when you have time I'm telling you only little suggestions.... I don't code in python so I couldn't improve it, but I'll try to code it for windows in c#. I know that brute force isn't the best way but this isn't to hack someone but only for educational purpose, and why not sometimes it could works ;)

> Does Instagram lock as well?

No, instagram module (for me) when in the list the software tries the passwords , even if it tests the right password it doesn't show that was the right word

**Comment by Ethical-H4CK3R** [comment]
that can be fixed with random delays.

**Comment by Virgula0** [comment]
Yeah it could, another thing from where you take proxy while cracking?

**Comment by deathsec** [comment]
Brute force attacks are the basics in the field of cyber security and they are indeed **powerfull** .
Do you know the Apple Cloud attack , when apple did'nt implement wrong password limiting , a huge 
number of Apple Cloud Accounts were hacked with brute force attack.
Brute force is powerful when you derive the wordlist from the victims personal info through permutation. ( **Just like in Mr.Robot** ) , all you need is a little social engineering!

You could use my **api** for instagram brute force attack , you do not really need to worry about locks and stuff because the api handles that too , checkout https://github.com/deathsec/Instagram-Py , I Just added a API long ago. its pretty stable!

**Comment by deathsec** [comment]
If possible i will create a tool for facebook too... in my free time , but I am really busy , final year high school ( You Know how that is , right?... )

**Comment by Ethical-H4CK3R** [comment]
Try the newer version called: [hyprPulse](https://github.com/Ethical-H4CK3R/hyprPulse)

**Comment by ethicalhacker8055** [comment]
Facebook password hack was coding...

**Comment by Ethical-H4CK3R** [comment]
What does that mean?
